import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import QueryProviders from "@/providers/QueryProvider";
import { ReactQueryStreamedHydration } from '@tanstack/react-query-next-experimental'

const inter = Inter({
  subsets: ["latin"], // required
  variable: "--font-inter", // optional if you want to use CSS variable
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <QueryProviders>
          <ReactQueryStreamedHydration>
            {children}
          </ReactQueryStreamedHydration>
        </QueryProviders>
      </body>
    </html>
  );
}
