import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Inter } from "next/font/google";
import QueryProviders from "@/providers/QueryProvider";

const inter = Inter({
  subsets: ["latin"], // required
  variable: "--font-inter", // optional if you want to use CSS variable
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <QueryProviders>{children}</QueryProviders>
      </body>
    </html>
  );
}
